server:
  port: 8889
  servlet:
    context-path: /core-service

spring:
  application:
    name: core-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: postgre
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /

logging:
  level:
    org:
      springframework:
        web: info
    ru:
      haazad:
        java:
          architectures: debug


